name: Build CryptoSignalPro

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build exe
        run: pyinstaller --onefile --name CryptoSignalPro bot.py
      - uses: actions/upload-artifact@v3
        with:
          name: CryptoSignalPro-windows
          path: dist/CryptoSignalPro.exe

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 python3-dev ffmpeg libncurses5
          pip install buildozer cython
      - name: Build APK
        run: |
          buildozer init
          echo "[app]\ntitle = CryptoSignalPro\npackage.name = cryptosignalpro\npackage.domain = org.example\nsource.dir = .\nsource.include_exts = py,png,jpg,kv,atlas\nversion = 0.1\nrequirements = python3,kivy,pandas,requests,python-binance,ta-lib\n\n[buildozer]\nlog_level = 2\nwarn_on_root = 1" > buildozer.spec
          buildozer android debug
      - uses: actions/upload-artifact@v3
        with:
          name: CryptoSignalPro-android
          path: bin/*.apk
